fix for "WHERE false" syntax issue
exasol/virtual-schemas pull request #416
Opened 2020-11-29 21:06 UTC by mwellbro

As shown in EXA-31110 the standard way of handling Boolean expr. led to an error in HANA because "WHERE false" is not valid syntax there.

This addition introduces a very barebone SapHanaSqlGenerationVisitor which will not ( like the standard one ) place the value for SQLConstant True or False but override this behavior with "1=0" (false) or "1=1" (true) which should be understood by any database , including HANA.

Had to test with an older v-schema version and only did positive-testing for now - should work as desired.

2020-11-30 06:03 UTC, redcatbear requested changes
Small rendering and editorial changes requested.

2020-11-30 06:03 UTC, redcatbear commented on src/main/java/com/exasol/adapter/dialects/saphana/SapHanaSqlGenerationVisitor.java
> +        }
```suggestion
    return literal:getValue() ? "1 = 1" : "1 = 0";
```

2020-11-30 06:08 UTC, redcatbear commented
Thanks for the contribution, @mwellbro.
I reviewed the code and have only editorial changes.

Until now the Hana dialect does not have automatic integration tests. I just found https://hub.docker.com/_/sap-hana-express-edition, which would allow us to tests with our usual [testcontainer](https://testcontainers.org) setup. No specialized testcontainer exists, but the [generic JDBC variant](https://www.testcontainers.org/modules/databases/jdbc/) will suffice anyway. We extract the dialects one-by-one from the bundle, when we do this for Hana, we can also add that integration test.

2020-11-30 06:20 UTC, redcatbear commented
Please update the version number by increasing the third digit (bugfix version). Then please run

```bash
mvn artifact-reference-checker:unify
```

Please also add an entry to the corresponding changelog file under `doc/ changes` (see other changelogs for examples) and add a link in `doc/changes/changelog.md`. This PR fixes issue #414 and it would be good to have that documentation for the PR in the changelog to not forget to add it.

2021-02-08 14:14 UTC, AnastasiiaSergienko commented
This pull request was moved to Hana repository and merged: https://github.com/exasol/hana-virtual-schema/pull/21

2021-02-08 14:14 UTC, closed without merging